services:
  db:
    image: postgres:17-alpine
    container_name: library-db
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: library_user
      POSTGRES_PASSWORD: library_pass
    ports:
      - "5432:5432"
    volumes:
      - library_pgdata:/var/lib/postgresql/data

volumes:
  library_pgdata:
