spring:
  application:
    name: library-api
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: library_user
    password: library_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
    secret: 5468697349734150726f6a656374536563726574466f724c6962726172794170694a5754
    expiration: 3600000